version: "3.8"
services:
  web:
    build: .
    container_name: hello_world
    ports:
      - "5000:5000"
    # volumes:
    #   - ./app:/app/app   # (opsional) aktifkan kalau mau live-reload saat dev
